Repository hisbaan/didyoumean, pull requests merged in 2022-04, with the labels that each got.

#6 Fix typo
  src/main.rs
Labels: bug

#7 Fix Powershell colorization
  src/main.rs
Labels: bug

#10 Insert words/distances in-place
  src/main.rs
Labels: optimization

#11 Tests
  src/lib.rs
  src/main.rs
  tests/integration_test.rs
Labels: documentation

#13 perf: ⚡️ edit distance
  Cargo.lock
  Cargo.toml
  benches/edit_distance.rs
  src/lib.rs
Labels: optimization

#14 perf: ⚡️ reduce runtime about 100ms compare to main branch
  benches/edit_distance.rs
  src/lib.rs
  src/main.rs
  tests/integration_test.rs
Labels: optimization
